### ISSUE TITLE
Do you have any ideas about the parameters created by png info?

### ISSUE THREAD

**Issue by Nomination-NRB** [hollowstrawberry/copy_png_info#1]
First of all,  thanks for your great work!

by the way
Why is the image parameter returned by the png info module not complete, if I want to use the api call to generate the image, then the png info module does not return enough parameters, there are many parameters that are not returned

**Comment by hollowstrawberry** [comment]
Oh hm, I'm not sure, it should show all parameters. Can you give me an example image that is causing you trouble?

**Comment by Nomination-NRB** [comment]
> Oh hm, I'm not sure, it should show all parameters. Can you give me an example image that is causing you trouble?

this format data is created by your function(select_source_file()):
```python
{
    "prompt": "shoes on the ground, consistent background colour, natural shadow of shoes on the ground",
    "negative_prompt": "Negative prompt: Abnormal light and shadow on the ground",
    "Steps": "41",
    "Sampler": "Euler a",
    "CFG scale": "7",
    "Seed": "783177188",
    "Size": "1048x1400",
    "Model hash": "346e4b5a73",
    "Model": "realisticVisionV60B1_v60B1InpaintingVAE",
    "VAE hash": "63aeecb90f",
    "VAE": "vae-ft-mse-840000-ema-pruned.ckpt",
    "Denoising strength": "0.75",
    "Conditional mask weight": "1.0",
    "Mask blur": "6",
    "Controlnet 0": {
        "Module": "lineart_realistic",
        "Model": "control_v11p_sd15_lineart [43d4be0d]",
        "Weight": "1.45",
        "Resize Mode": "Crop and Resize",
        "Low Vram": "False",
        "Processor Res": "512",
        "Guidance Start": "0",
        "Guidance End": "1",
        "Pixel Perfect": "True",
        "Control Mode": "Balanced",
        "Save Detected Map": "True"
    },
    "Version": "v1.7.0"
}

```

but if I use api to use stable diffusion, I need more parameters, for example:
```python
payload = {
        "prompt": promptList[0],
        "negative_prompt": promptList[1],
        "init_images": [img],
        "mask": mask,
        "resize_mode": 1,  # Resize mode: [Just resize, Crop and resize, Resize and fill, Just resize(latent upscale)]
        "mask_blur": 4,  # Mask blur: 0-64 
        "inpainting_fill": 1,  # Masked content: [fill, original, latent noise, latent nothing]
        "inpaint_full_res": Inpaint_area,  # Inpaint area: [Whole picture(False), Only masked(True)]
        "sampler_name": Sampling_method,  # Sampling method
        "inpaint_full_res_padding": 32,  # Only masked padding, pixels
        "steps": Sampling_steps,  # Sampling steps
        "inpainting_mask_invert": 0,  # mask mode 0 inpaint masked, 1 inpaint inclusive masked
        "width": width,  # Resize to Width
        "height": height,  # Resize to Height
        "batch_size": 1,  # Batch count
        "batch_count": 1,  # Batch size
        "cfg_scale": 7,  # CFG Scale
        "denoising_strength": Denoising_strength,  # Denoising strength
        "seed": -1,
        "alwayson_scripts": {
            "ControlNet": {
                "args": [
                    {
                        "input_image": controlnet0_input,
                        "enabled": True,  # Enable tick
                        "module": controlnet0_module,  # Preprocessor
                        "model": controlnet0Key_para['model'],  # Model
                        "weight": controlnet0_weight,  # Control Weight
                        "guidance_start": 0.0,  # Starting Control Step
                        "guidance_end": 1.0,  # Ending Control Step
                        "processor_res": 512,
                        "control_mode": controlnet0_control_mode,  # Control Mode: [Balanced, My is m imp, C is m imp]
                        "resize_mode": 1,  # Resize Mode: [Just Resize, Crop and Resize, Resize and Fill]
                        "pixel_perfect": eval(controlnet0_pixel),
                    },
                    {
                        "enabled": False,  # Enable tick
                    },
                    {
                        "enabled": False,  # Enable tick
                    },
                    {
                        "enabled": False,  # Enable tick
                    }
                ]
            }
        }
    }

```
Initially I wanted to use the webui version to debug the best output parameters, then use your repository to get and format the parameters used for the images, and then migrate to the use of the api, but found that the parameters obtained from the images were not complete enough to call the api

**Comment by hollowstrawberry** [comment]
The api example you showed had 2 more controlnet images than the output example you showed, so it's much longer. But other than that, it's just a different format. You'll have to use some code to change from one format to the other, and to fill the missing paremeters. Note that it's possible that some parameters are not saved to the image, and you have to infer these yourself, or they are simply lost with no way to retrieve them.

**Comment by Nomination-NRB** [comment]
> The api example you showed had 2 more controlnet images than the output example you showed, so it's much longer. But other than that, it's just a different format. You'll have to use some code to change from one format to the other, and to fill the missing paremeters. Note that it's possible that some parameters are not saved to the image, and you have to infer these yourself, or they are simply lost with no way to retrieve them.

Yes, I found that some parameters were not written into the picture, so those parameters were not parsed out. Thank you for your reply (such as: inpainting_fill, inpaint_full_res
